GovWifi/govwifi-logging-api

app.rb

The loadbalancer sends requests to this endpoint to determine whether
the node is healthy.

Expose a health check route

---

app.rb
config.ru
lib/session.rb
lib/user.rb
mysql/schema.sql
spec/features/post_auth_spec.rb
spec/spec_helper.rb

Implement functionality of current backend when dealing with PostAuth.
It creates session records, updates userdetails, and emits different http status codes based on certain conditions.  
There is still a bit of work to do around edge cases like when some values are not present in the URL (which happens frequently).  This will be addressed in the next PR, along with refactoring of the production code.

Post Authentication

---

app.rb

We will log requests to CloudWatch on staging and production

Enable logging

---

app.rb
lib/logging/post_auth.rb

Create a simple object to do the post authentication and return whether
it was successful or not.

Refactor Post Authentication functionality out of app.rb

---

config.ru

This will report errors to Sentry for debugging

Enable Sentry

---

lib/performance_platform/repository/session.rb
spec/lib/performance_platform/gateway/unique_users_spec.rb

We had a bug where we were getting incorrect statistics.
This fixes it.

Fix the query for unique users and also improve the tests

---

lib/performance_platform/gateway/account_usage.rb
lib/performance_platform/repository/session.rb
spec/lib/performance_platform/gateway/account_usage_spec.rb
spec/lib/performance_platform/use_case/send_performance_report_spec.rb
tasks/publish_statistics.rb

Statistics for account usage should be sent on daily,
weekly amd monhtly periods.

Add daily and monthly periods to account usage

---

tasks/publish_statistics.rb

Other periods of statistics removed in this commit are
calculated by the dashboard itself.

Remove unecessary statistics calls

---

spec/lib/performance_platform/gateway/account_usage_spec.rb

I wasn't confident in the behaviour of the performance platform, so I did a little digging around the tests to confirm. I decided on a plan of refactoring the existing tests so it would be much easier to switch over to the new query and data source.
This PR only has the refactoring commit at the moment - the second part of this should now be pretty straightforward, but perhaps it should be in a second PR?

Refactor account usage specs

---

app.rb

`production` is set to `INFO` and all else `DEBUG`

Set appropriate log levels for production and non-production envs

---

Jenkinsfile

Like https://github.com/alphagov/govwifi-authentication-api/pull/37, but simpler because there's only one region (so far).
Tried this out with the existing pipeline, all working fine.

Autodeploy to staging, one-click deploy to prod

---

Jenkinsfile

this is dealt with by Jenkins' multi-branch builds

remove explicit notifier to github status API

---

Jenkinsfile

this allows us to launch it without an agent, so we don't block an executor

break out user confirmation into a seperate stage

---

Jenkinsfile

Remove call to non-existant method

---

lib/gdpr/gateway/session.rb
tasks/session_deletion.rb

We want to see the number of rows affected by each run so we can debug
it more easily

Print more details about the daily session deletion

---

lib/logging/post_auth.rb
spec/features/post_auth_spec.rb

Reverts alphagov/govwifi-logging-api#110

Revert "Don't populate last_login for users"

---

Makefile
docker-compose.yml
lib/loader.rb
lib/user.rb
mysql_user/Dockerfile
mysql_user/bin/wait_for_mysql
mysql_user/schema.sql
spec/features/certs_logging_spec.rb
spec/features/post_auth_spec.rb

This is needed to update the last_login of the user

Read userdetails from the new user database

---

app.rb

This seems to be causing a huge memory / cpu spike.
Testing whether this fixes it

Undo logging

---

lib/logging/post_auth.rb
spec/features/post_auth_spec.rb

See if this decreases the load on the logging api

Stop writing to last_login

---

lib/logging/post_auth.rb
spec/features/post_auth_spec.rb

This reverts commit dcc22f9751c16e4367631429627e8381af04f326.

Revert "Stop writing to last_login (#121)"

---

Makefile
ci/pipelines/pr.yml
ci/tasks/lint.yml
ci/tasks/pre-build.yml
ci/tasks/scripts/lint.sh
ci/tasks/scripts/pre-build.sh
ci/tasks/scripts/test.sh
ci/tasks/scripts/with-docker.sh
ci/tasks/test.yml
ci/variables.md
docker-compose.concourse.yml

Based on https://github.com/cybojenix/govwifi-concourse-pr-template/tree/master/govwifi-pr

Add in Concourse PR pipeline

---

lib/performance_platform/presenter/roaming_users.rb
tasks/publish_statistics.rb

This enables publishing roaming statistics.

Publish roaming user stats weekly and monthly

---

README.md

We no longer publish Account usage and Unique users statistics, update
documentation to refer to only weekly and monthly tasks

Update README to refer to weekly and monthly statistics

---

lib/volumetrics/use_case/sync_s3_to_elasticsearch.rb
spec/lib/volumetrics/use_case/sync_s3_to_elasticsearch_spec.rb

Adjust S3 gateway parameters
Due do a separate PR, the args for this have changed, and need updated.

Update full S3->ES sync task to conform to adjusted S3 gateway

---

lib/performance/gateway/s3.rb

Add debugging on S3 failure.
S3's being a pain and not letting us do what it's configured to do.

Output some logging when Aws::S3::Errors::AccessDenied occurs

---

lib/metrics/metric_sender.rb
lib/performance_platform/gateway/active_users.rb
lib/performance_platform/gateway/completion_rate.rb
lib/performance_platform/gateway/roaming_users.rb
lib/performance_platform/gateway/volumetrics.rb
spec/lib/metrics/metric_sender_spec.rb
spec/lib/performance_platform/gateway/active_users_spec.rb
spec/lib/performance_platform/gateway/completion_rate_spec.rb
spec/lib/performance_platform/gateway/roaming_users_spec.rb
spec/lib/performance_platform/gateway/volumetrics_spec.rb

When gathering metrics we need to add the date the metric were obtained.

Add date stamp to metrics

---

lib/performance/metrics/metric_sender.rb
tasks/publish_metrics_to_elasticsearch.rb
tasks/publish_statistics.rb

The constants in the metrics Rake tasks were wrong and have been fixed

Wrong constants fixed in metric Rake tasks

---

lib/performance/repository/session.rb

In the roaming users count query.
Since the table only contains just over a months worth of data (at
least in production), when you're querying for most of it, I don't
think this index is the effective one to use.
Link to Trello card: https://trello.com/c/tWoyciKg/2056-investigate-sentry-sequeldatabaseerror

Only suggest an index for short time periods

---

lib/performance/repository/sign_up.rb
spec/factories/user_details.rb
spec/lib/performance/use_case/completion_rate_spec.rb
spec/lib/performance/use_case/volumetrics_spec.rb

Update the completion rate data collection code and specs
The completion data that was gathered was not very well tested and
some slight discrepancies were present.
This version of the completion rate code explicitly tests we're
gathering the exact data required
https://trello.com/c/yRa3gd0W/2264-create-data-chart-on-grafana-to-show-new-users-that-have-signed-in

Update the completion rate data collection code and specs

---

buildspec.yml

Introduce an AWS Codebuild task permitting us to migrate from concourse to AWS Developer Tools
We need to migrate away from Concourse due to strategic decision to use managed services.
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-253

Introduce an AWS Codebuild task using a new buildspec.yml file.

---

entrypoint.sh

Add logging message to show database migration has started
So we can see what is happening while the app is deployed

Add logging message to show database migration has started

---

Makefile
create_user_details.sh
lib/performance/metrics/metric_sender.rb
lib/performance/repository/sign_up.rb
lib/performance/use_case/new_users.rb
spec/lib/performance/use_case/new_users_spec.rb

Calculate the number of new users of the previous month and split them out in users that managed to connect successfully and the ones that were unsuccessful.
We need to report on these statistics and so automating harvesting these makes our job easier
Link to Jira card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-1414

Inactive users

---

lib/performance/use_case/new_users.rb
spec/lib/performance/use_case/new_users_spec.rb

This fixes a bug which stops the new users metric from running monthly

Fix new users metric

---

Makefile

Fix Test and Lint
Command with dash is now deprecated. Fixing.

Fix Test and Lint

---

Gemfile
Gemfile.lock
lib/performance/repository/session.rb
lib/performance/use_case/roaming_users.rb
spec/factories/sessions.rb
spec/lib/performance/metrics/metric_sender_spec.rb
spec/lib/performance/use_case/roaming_users_spec.rb
spec/spec_helper.rb

Count the number of CBA users and send to Grafana (Elasticsearch / S3) 
We would like to know how many people use CBA
https://technologyprogramme.atlassian.net/browse/GW-1754

Count cba users

---

.github/workflows/update-ruby.yml

Fix issue with permission
Action was failing due to missing permissions, somehow got missed.

fix fix permissions, add labeller.
