GovWifi/govwifi-logging-api

app.rb, lib/mac_formatter.rb, spec/lib/mac_formatter_spec.rb
Preserve existing MAC formatting functionality from the existing PHP
backend.
We want to ensure that the MAC is in a good format before persisting it
in the session table.
There are some edge cases where we still end up with an invalid MAC.
I have documented this with RSpec examples.
Leaving this as is for now, can revisit later, but ultimately we expect
that the supplied MAC address is in a good format by the end user.
Functionality from here: https://github.com/alphagov/govwifi/blob/master/src/AAA.php#L329
=> Introduce a MAC Formatter

app.rb, spec/features/post_auth_spec.rb
It is not garuanteed that we will receive all the parameters from the
radius servers.
Based on the functionality of the current backend, we will persist empty values.
This even applies to the username which doesn't make much sense because
it cannot be used to identify the indivdual that was authorised.
This functionality can be changed once this current implementation has
been proven to work in production.
=> Make parameters in post-auth route optional

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
The "Called Station ID" param can contain either an access point value
or a building identifier.  Once formatted, we can see if it is 17 chars
long and know that it is an acces point identifier.  If it is not blank
and not a valid MAC, we can assume that it is a building identifier.
Persist either the ap or the building identifier.
=> Ensure either the access point or the building identifier is set

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
This functionality was missing, so add it with this commit.
When we create a session record, we populate the start time with the
current time.
Also fix date format with strftime in for userdetails last_login, it was
using %y which is a date like 18, not 2018. MYSQL overlooked this and
saved it correctly anyway, but fix the code for consistency.
=> Record start time for a session

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
Previously we would save the username exactly as it came in from the url parameters.
Current backend behaviour always ensures that the username is presisted in uppercase, so preserve this functionality.
=> Usernames are always saved as uppercase

app.rb, lib/loader.rb, lib/performance_platform/gateway/account_usage.rb, lib/performance_platform/repository/session.rb, spec/lib/performance_platform/gateway/account_usage_spec.rb
This is the basic functionality to get the statistics from the database
in raw form.
A later commit will introduce a presenter to transform
these results into something the performance platform will accept.
Nothing uses this yet, a later commit will introduce the rake task to
send these over to the performance platform.
=> Generate statistics for sessions from the database

Gemfile, Gemfile.lock, Rakefile, app.rb, config.ru, lib/common/base64.rb, lib/loader.rb, lib/performance_platform/gateway/performance_report.rb, lib/performance_platform/presenter/account_usage.rb, lib/performance_platform/use_case/send_performance_report.rb, spec/lib/common/base64_spec.rb, spec/lib/performance_platform/gateway/performance_report_spec.rb, spec/lib/performance_platform/use_case/send_performance_report_spec.rb, spec/spec_helper.rb, tasks/publish_statistics.rb
Remaining required functionality for sending over AccountUsage statistics.
This introduces the use cases to send the correctly formatted data over
to the performance platform.
Also some minor refactoring.
=> Send performance stats

lib/loader.rb
We're running into issue where a long running sql query (roughly 10
minutes) is being cancelled by the ruby client.
We suspect that increasing this timeout value will prevent this from
happening but needs to be tested against the production dataset.
Set the timeout to 9999, which should be more than enough time
=> Increase the read timeout for Sequel gem

lib/loader.rb
We are seeing an error in production where Base64 is not required.
Our automated tests aren't picking this up but we suspect it's being
required by a testing library.
Explicitly require base64 so we can use it.
=> Explicitly require base64

lib/loader.rb
Same error as with the Base64 library it seems we have to explicitly
require net/http.
Once again some test library must be including this which means we don't
see the same errors in production as in the test environment.
=> Require Net/Http explicitly

lib/loader.rb
Similar to previous issues, we don't have a JSON library available in
the production environment (but we do in the test environment), so add
it.
=> Require JSON library explicitly

lib/performance_platform/gateway/account_usage.rb, lib/performance_platform/repository/session.rb, spec/lib/performance_platform/gateway/account_usage_spec.rb, spec/lib/performance_platform/use_case/send_performance_report_spec.rb
In particular roaming statistics are most useful when computed
against a period of a week instead of a day because it's more
likely that people will travel between government buildings
in that period, not in a single day.
=> Aggregate account usage statistics by week instead of a day

lib/performance_platform/repository/session.rb
Simplifying this query turned out to break it.
Restored the original query but had trouble testing this since the
Sequel gem converts date values into date objects.  Trying to group by
these date objects doesn't work as expected.
Introduce an extra step in ruby to do the grouping.
There will be no performance impact, and the amount of rows returned is
small
=> Fix query for unique user statistics

lib/performance_platform/repository/session.rb, spec/lib/performance_platform/gateway/account_usage_spec.rb
Aggregation should be done on the dashboard side instead of
on the SQL side.
=> Revert to non-aggregated version of account usage

lib/performance_platform/use_case/send_performance_report.rb, spec/lib/performance_platform/use_case/send_performance_report_spec.rb
We use Rake tasks which don't have access to the Rack logger, so we use
the logger from the Ruby standard library.
This is so we can have better visibility over what the rake tasks are
doing.
Unlike the Rack logger, we cannot switch this off in the test
environment with a configuration.  Pull out the dependency on the
logger, and inject a fake during testing.
=> Silence Logger in test environment

lib/performance_platform/presenter/unique_users.rb, spec/lib/performance_platform/use_case/send_performance_report_spec.rb
Different periods on unique-users statistics for Performance
platform use different key names.
=> Use different count key names on unique users periods

Dockerfile, Gemfile, Gemfile.lock, lib/performance_platform/gateway/s3_ip_locations.rb, lib/performance_platform/gateway/sequel_ip_locations.rb, lib/performance_platform/use_case/synchronize_ip_locations.rb, mysql/schema.sql, spec/features/publish_daily_statistics_spec.rb, spec/lib/performance_platform/gateway/sequel_ip_locations_spec.rb, spec/lib/performance_platform/use_case/synchronize_ip_locations_spec.rb, spec/spec_helper.rb, tasks/publish_statistics.rb
This PR fetches mappings (of the form { ip: '123.123.123.123', location_id: '1' }) from the configured s3 bucket, and saves them to the `ip_locations` table.
This use case is used by the `synchronize_ip_locations` rake task, which'll be called before we `publish_daily_statistics`. 
This means we can properly identify which requests are users roaming between different locations.
Not locally tested yet, and a few bits I'm less happy with and want input on.
=> Fetch ip-location mapping from s3 bucket

lib/performance_platform/repository/session.rb, spec/lib/performance_platform/gateway/account_usage_spec.rb
This is the followup to #46.
This PR changes the expected data source for ip/location links when calculating 'account usage', from `site_ip` and `site` to just `ip_locations`.
(note that this PR doesn't point at master - this is for an easier diff, can change target once #46 is in)
=> Change source table for roaming 'account usage'

README.md, lib/performance_platform/gateway/account_usage.rb, lib/performance_platform/gateway/unique_users.rb, lib/performance_platform/presenter/account_usage.rb, lib/performance_platform/presenter/unique_users.rb, lib/performance_platform/repository/session.rb, spec/lib/performance_platform/gateway/account_usage_spec.rb, spec/lib/performance_platform/gateway/unique_users_spec.rb, tasks/publish_statistics.rb
We are seeing gaps in our performance platform statistics, we are unable
to find the root cause of this.
Allow overriding the date to backfill missing data for now
=> Allow date overrides for rake tasks

Jenkinsfile
We've had some "hanging" docker containers on Jenkins that block
other builds - this PR makes sure `make stop` is always run, even in
cases of the build being aborted or crashing.
=> Kill docker containers every CI build

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
This is so we can provide meaningful information through admin to GovWifi organisations
=> Log data for 'access-reject' auth requests

Gemfile.lock, lib/logging/post_auth.rb, lib/performance_platform/repository/session.rb, mysql/schema.sql, spec/features/post_auth_spec.rb, spec/lib/performance_platform/gateway/account_usage_spec.rb
- Add `success` column to `sessions` table
- Set `success` boolean based on access accept/reject
- Ensure that only successful sessions are sent to performance platform
=> Save success status on sessions table

app.rb, spec/features/search_sessions_spec.rb
- Exposes a GET '/authentication/events/search/:username' endpoint
- This endpoint will be queried by the Admin rails app for user logs.
- Limits search to last 100 sessions. This is just a finger in the air guess at what is an appropriate rate limit.
- Has no limitation on what location these sessions were created from. The Admin portal will be responsible for any kind of filtering based on permissions / ownership of data / IPs / Locations etc.
=> Search authentication events by username endpoint

app.rb
When we were reviewing the logs setup for the apps, we noticed that full blown stack traces are making lots of noise in there, when we already have Sentry setup for these sorts of things.
=> Don't output stacktraces to the logs for staging and production

lib/gdpr/gateway/session.rb, lib/gdpr/use_case/session_deletion.rb, lib/loader.rb, spec/features/daily_session_deletion_spec.rb, spec/lib/gdpr/gateway/session_spec.rb, spec/lib/gdpr/use_case/session_deletion_spec.rb, tasks/session_deletion.rb
We are deprecating the Lambda functions to keep us GDPR compliant since
most of our cron tasks run in ECS.  Better to have only one service do
all the crons.
This will run daily and delete sessions older than 3 months.
=> Run Session Deletion as an ECS Scheduled Task

Rakefile
Rake doesn't auto discover tasks; you have to manually include it.
=> Auto Load Session Deletion Rake Task

tasks/publish_statistics.rb
Since we changed the reporting to accept an 'override date' to backfill
missing data, we missed assigning the default date if no override
date was given.
This fixes it and ensures a date is always present for reporting.
=> Fix error with reporting weekly and monthly stats

Gemfile, Gemfile.lock, app.rb, config.ru
Sets up [sensible_logging](https://github.com/madetech/sensible_logging) gem which provides:
* Tagged logging
* Request ID (for tagged logging, and to include in Sentry exceptions in future)
* Minimal request log format
Example output from request logging:
```
[localhost] [development] [76b706bf-7f0c-48ec-8045-57a40d5aad82] method=GET path=/healthcheck status=200 duration=0.0207032 params={"test"=>"one", "two"=>"three"}
```
If you reference the built in Sinatra `logger` helper within the app/routes, then you'll see output like:
```
get 'healthcheck' do
logger.debug('testing')
'Healthcheck'
end
```
```
[localhost] [development] [76b706bf-7f0c-48ec-8045-57a40d5aad82] testing
[localhost] [development] [76b706bf-7f0c-48ec-8045-57a40d5aad82] method=GET path=/healthcheck status=200 …
```
=> Setup and configure sensible_logging gem

lib/gdpr/gateway/session.rb, spec/lib/gdpr/gateway/session_spec.rb
The maximum amount of session data we need to do reporting is 1 month.
Originally we kept more than this to facilitate with criminal investigations,
this can still be done using Cloudwatch instead of the database.
This should reduce the size of the sessions table by 2 thirds, making it
less difficult to manage and enabling us to switch to a less expensive
RDS image down the line.
=> Keep less session data in the database

app.rb, lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
Given Logging has been removed from the "critical path", we never want
it to influence the result of the radius request based on a logging
operation.
If the logging API returns a 404, it will implicitly change an
Access-Accept to an Access-Reject.  We never want this to happen.
Always return a 204, indicating to the radius servers that everything
has gone well.
=> Never return 404

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
This will now be done by the authorisation API when a user attempts a
login.
By making this change, this API won't need access to the users
table at all.
=> Don't populate last_login for users

app.rb, lib/logging/post_auth.rb, spec/features/get_method_certs_logging_spec.rb, spec/features/get_method_post_auth_spec.rb, spec/features/post_method_certs_logging_spec.rb, spec/features/post_method_post_auth_spec.rb
Added a `POST` endpoint for the `post-auth` request from RADIUS. I've added this on top of the existing `GET` request so we can have a smooth transition from `GET` to `POST` from the frontends.
The specs have been duplicated, one for `post_method_` and one for `get_method_`.
=> Add a POST endpoint for the post-auth request

app.rb
You can only read a POST request once, and it has to be rewinded if you
want to read it again.  We need to read it twice, once for logging to
CloudWatch and once for storing it in the database.
=> Rewind the request body for logging post requests

mysql_user/bin/wait_for_mysql
this was causing a silent failure, which prevented Make from waiting for the user db
=> add shebang to wait_for_mysql

app.rb
Sentry has to be configured differently for Rake and Sinatra.
Only 'use' Sentry for Sinatra when it's been defined for the correct
environment.
=> Ensure Sentry is reporting for both Rake and web requests

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
this will reduce the overhead of updating the users last login, and means
we can avoid the logic for if the user doesn't exist
=> use an update instead of a read + update

Jenkinsfile
- When there is a merge to `logging-api/master` it triggers the `acceptance-tests/master` pipeline to be built.
- This runs the acceptance tests on all the dependent master branches.
- If it fails it blocks the deploy, but not the merge.
Exists in the `frontend` already here: https://github.com/alphagov/govwifi-frontend/blob/master/Jenkinsfile#L33
=> Run acceptance specs when a merge to master occurs

lib/loader.rb
We've been running out of connections when under load, so increase the [pool size from 4][2].
This takes us from 12 connections to 48 connections per regional db\*, which is well within our limits\*\*.
16 has been chosen so we can have a DB connection [per thread][1]. Given that this service
is a thin wrapper around the database, the requests will immediately wait. Aligning thread
count with the connection pool size should avoid this issue.
For the user database, authentication services only access the read replicas, while the logging service hits the master.
The result is the increase in database load will have a negligible effect on authentication.
\*: connection count is based on pool size per instance, 3 instances per region
\*\*: limit per db is based on memory size of db. Ours has …
=> increase the database connections to 16 per pool

Dockerfile
- since alpine 3.3, we've been able to run apk in 'no-cache' mode.
This handles cleanup for us, which means we can stop running the cleanup
commands manually.
This specifically targets the 'find / ...' command, which fails when utilising
namespace remapping with Docker, as we get a 'Permission Denied' error when accessing
files in '/proc/'
=> simply the package installation process

lib/performance_platform/gateway/active_users.rb, lib/performance_platform/presenter/active_users.rb, spec/lib/performance_platform/gateway/active_users_spec.rb, spec/lib/performance_platform/use_case/send_performance_report_spec.rb
The total is no longer used and instead of `transactions` we now use `users`.
=> Remove total key and value from active users performance platform stats

lib/performance_platform/gateway/roaming_users.rb, lib/performance_platform/repository/session.rb, spec/lib/performance_platform/gateway/roaming_users_spec.rb
Add roaming user statistics
This new statistic will take the number of roaming users divided by the
number of active users.  This will be sent to the performance platform
as a new statistic.
The rake task doesn't call this yet.
=> Roaming users

lib/performance_platform/gateway/roaming_users.rb, lib/performance_platform/presenter/roaming_users.rb, spec/lib/performance_platform/gateway/roaming_users_spec.rb, spec/lib/performance_platform/presenters/roaming_users_spec.rb
We need to only send active users and roaming users stats.
The percentage will be calculated by the performance platform.
=> Modify roaming performance platform payload

lib/logging/post_auth.rb, spec/features/post_auth_spec.rb
We're reached a critical point where this is causing major lag on the user database.
Disable this functionality for now.
=> HOTFIX: stop updating last_login on the user table

mysql_user/Dockerfile
This matches our hosted environment.
We need to use mysql_native_password, as mariadb client doesn't ship with this yet
=> change to using mysql 8 For the UserDB

lib/gdpr/gateway/session.rb
Currently when the deletion of old sessions happens, a lag
in RDS replication occurs, which in turn fires a cloudwatch
alarm.  As it self heals, this alarm is ignored but it does
create uneccessary noise which we have all become numb to.
We beleive the cause is because of how large the query is,
and that it creates a single large transaction log which
needs to be first copied across and fully replayed on the
replica, and during this replay the lag is created.
This PR breaks the session deletion query into batches of
100, with the intent to allow each batch to be replicated
and replayed on to the replica whilst other batches are
still being created on the master, thus dampening the
effect of the replication and reducing lag.
Pair: @smford & @rjbaker
=> Adjust Batch deletion of old sessions to reduce RDS lag

tasks/publish_statistics.rb
The monthly and weekly tasks are identical except for the SQL keyword
used to chunk up the data. Leverage this with a single task redefined
for each period (day/week/month) through a mapping that also holds the
corresponding adverbial (daily/weekly/monthly) for use in the task
name (manually inferring it is awkward: `"#{period}ly"` doesn't work
for `day`).
=> feature: add daily reporting for the publish_statistics task

ci/pipelines/pr.yml
Fixes an error caused by a change to the yml parser used on CI. Similar to alphagov/govwifi-acceptance-tests#25
=> FIX: Move yml anchor declaration above usage

lib/metrics/active_users.rb, spec/lib/metrics/active_users_spec.rb
But keep the `active-users` prefix so that downloading a file on its
own (i.e without the folder name) still makes sense.
=> fix: put the active users metrics into their own folder

lib/metrics/active_users.rb, lib/metrics/roaming_users.rb, lib/metrics/s3_publisher.rb, lib/performance_platform/gateway/s3_ip_locations.rb, lib/services.rb, spec/lib/metrics/active_users_spec.rb, spec/lib/metrics/roaming_users_spec.rb, spec/lib/metrics/s3_fake_client.rb, tasks/publish_statistics.rb
Data points about roaming users that are normally sent to the PP
are now also sent to an S3 bucket.
Trello: https://trello.com/c/lG7cmIzF/408-upload-roamingusers-data-points-to-s3
=> Add the roaming_users data points to the S3 Bucket

tasks/publish_statistics.rb
Fixes a bug in the `synchronize_ip_locations` rake task
=> Allow Metrics::IPSynchronizer to be called using a class method

README.md, lib/loader.rb, lib/metrics/active_users.rb, lib/metrics/roaming_users.rb, lib/performance_platform/gateway/active_users.rb, lib/performance_platform/gateway/performance_report.rb, lib/performance_platform/gateway/roaming_users.rb, lib/performance_platform/gateway/s3_ip_locations.rb, lib/performance_platform/presenter/active_users.rb, lib/performance_platform/presenter/roaming_users.rb, lib/performance_platform/presenter/unique_users.rb, lib/performance_platform/repository/session.rb, lib/performance_platform/use_case/send_performance_report.rb, spec/lib/performance_platform/gateway/active_users_spec.rb, spec/lib/performance_platform/gateway/performance_report_spec.rb, spec/lib/performance_platform/gateway/roaming_users_spec.rb, spec/lib/performance_platform/presenters/roaming_users_spec.rb, spec/lib/performance_platform/use_case/send_performance_report_spec.rb, tasks/publish_statistics.rb
Reverts alphagov/govwifi-logging-api#333
We're going to remove these rake tasks later as PP retirement is currently put on hold for sometime.
=> Revert "Remove rake tasks and code to send stats to the performance platform"

ci/tasks/build-deployable.yml
Add Docker Hub auth token to allow the Concourse pipeline task to pull images from Docker Hub.
The pipeline is configured in [govwifi-concourse-deploy-pipeline](https://github.com/alphagov/govwifi-concourse-deploy-pipeline).
We need to do this because Docker Hub will introduce rate limiting on 1 November.
paired: @camdesgov & @sarahseewhy
=> Add Docker Hub auth token to build-deployable

Gemfile, Gemfile.lock, Rakefile, lib/loader.rb, lib/volumetrics/gateway/elasticsearch.rb, lib/volumetrics/gateway/s3.rb, lib/volumetrics/use_case/sync_s3_to_elasticsearch.rb, spec/lib/metrics/s3_fake_client.rb, spec/lib/volumetrics/gateway/elasticsearch_spec.rb, spec/lib/volumetrics/gateway/s3_spec.rb, spec/lib/volumetrics/use_case/sync_s3_to_elasticsearch_spec.rb, tasks/sync_s3_volumetric.rb, tasks/sync_s3_volumetrics.rb
Add a rake task to read volumetric objects in S3, and write them to the ElasticSearch volumetrics index.
When we install ES we need to populate it with historical performance data. We also need a disaster recovery mechanism to restore performance data from a backup.
https://trello.com/c/4sQz7DZm
=> Add rake task to sync S3 volumetrics with ElasticSearch

lib/loader.rb, lib/services.rb, lib/volumetrics/gateway/elasticsearch.rb, lib/volumetrics/repository/sign_up.rb, lib/volumetrics/use_case/fetch_data.rb, lib/volumetrics/use_case/send_to_elasticsearch.rb, spec/lib/volumetrics/gateway/elasticsearch_spec.rb, spec/lib/volumetrics/use_case/fetch_data_spec.rb, spec/lib/volumetrics/use_case/send_to_elasticsearch_spec.rb, tasks/publish_metrics_to_elasticsearch.rb
Adds a rake task to send a volumetrics data point to Elasticsearch.
Previously such tasks were located in the User signup api. We are moving them all to the logging api so that
there is one place where all metrics code is, which makes code sharing and finding code easier.
Trello: https://trello.com/c/RH2Q1Fk6/1027-3-update-rake-tasks-to-upload-data-points-to-elastic-search
=> Send a Volumetrics data point to Elasticsearch

tasks/publish_metrics_to_elasticsearch.rb
Add missing PERIODS constant and logger definition.
=> Fix publish_metricst_to_elasticsearch rake task

tasks/sync_s3_volumetrics.rb
Fix S3 bucket names
Because the old ones aren't correct.
=> Correct S3 bucket names

tasks/publish_metrics_to_elasticsearch.rb, tasks/publish_statistics.rb
- The MetricSender needs to include all module names
- The PERIODS constant was redefined. Use the one from the MetricSender
=> Fixes in metrics rake tasks

lib/performance/metrics.rb, lib/performance/metrics/metric_sender.rb, spec/lib/performance/metrics/metric_sender_spec.rb, tasks/sync_s3_volumetrics.rb
All performance metrics now use one index in ElasticSearch
We can easily differentiate between metrics using the 'metric_name'
attribute and using one index allows us to show multiple metrics
in one dashboard in Grafana
Link to Trello card (if applicable): https://trello.com/c/ThQ5YdQB/1297-story-3-the-volume-of-unique-users-who-use-the-service-on-a-monthly-basis
=> All metrics now use one index in Elasticsearch

lib/performance/metrics.rb
Elasticsearch indices should be lowercase
Otherwise an exception is thrown
=> Elasticsearch indices should be lowercase

ci/tasks/scripts/migrate.sh
Fix cluster name in migrate.sh script
Or the cluster can't be found on deploy
=> Fix cluster name in migrate.sh script

.secrets.baseline, lib/logging/post_auth.rb, mysql/migrations/20210727141200_add_task_id_to_sessions.rb, spec/features/certs_logging_spec.rb, spec/features/post_auth_spec.rb
The task_id parameter has recently been added to the Radius rest
plugin's post-auth hook.
This PR enables this parameter to be stored.
We want to be able to surface this in the admin portal
https://trello.com/c/htMbaqCQ/1469-show-which-radius-server-was-used-to-serve-a-request-in-the-admin-portal2
see also: https://github.com/alphagov/govwifi-frontend/pull/143
=> Add task_id to session logging.

Dockerfile, Makefile, entrypoint.sh
The database migration should run everytime the docker
container starts and before the application runs.
The acceptance frontend tests won't run properly because it does not use the Makefile
which means the migrations don't run
=> Move database migration step to entrypoint

Rakefile, lib/performance/gateway/elasticsearch.rb, lib/performance/metrics/request_stats_sender.rb, lib/performance/repository/session.rb, spec/lib/performance/metrics/request_stats_sender_spec.rb, tasks/send_request_statistics.rb
Add a Rake task to send a list of IP addresses and the number of failed and successful requests each to Elasticsearch.
We want to be able to visualise the number of failed and successful requests per IP address in Grafana
https://trello.com/c/iuIWfaxw/1502-super-admin-time-series-of-org-traffic-3
=> Add a Rake task to send a list of IP addresses and the number of failed and successful requests to Elasticsearch.

tasks/send_request_statistics.rb
Make send_request_statistics rake task load the environment
Otherwise it can't find any of the classes it depends on
=> Make send_request_statistics rake task load the environment

lib/performance/gateway/elasticsearch.rb, spec/lib/performance/metrics/request_stats_sender_spec.rb
Elasticsearch requires a very specific array to be sent as part of
a bulk indexing operation. This commit implements that correctly.
Otherwise Elasticsearch will reject the bulk upload.
=> Fix the bulk upload code.

lib/performance/repository/session.rb, spec/lib/performance/metrics/request_stats_sender_spec.rb
Format the timestamp in a way that Elasticsearch understands
Otherwise Elasticsearch will interpret the 'time' column to be a String
datatype instead of a Date one
=> Format the timestamp in a way that Elasticsearch understands

mysql/migrations/20210906124800_add_start_site_ip_success_index_to_sessions.rb
Index the Sessions table on start, siteIP, success
This facilitates queries such as
select count(*) from sessions where siteIP="x.x.x.x" and start>SUBDATE(NOW(),1) and success=1;
which are performed regularly in the the admin portal
Link to Trello card (if applicable): https://trello.com/c/QMqQGD6i/1545-handle-504-when-accessing-hmctss-page-in-the-super-admin-site
=> Add a new index to the sessions table

lib/services.rb
Memoize S3 and Elasticsearch client
To ensure we do not instantiate this multiple times.
We sometimes call ```Services.s3_client``` in a loop which can potentially cause faults
(for instance here: https://github.com/alphagov/govwifi-logging-api/blob/d2ce6a7249ce1361f50be2891a1f5ff1b87c1445/lib/performance/gateway/s3.rb#L11)
https://trello.com/c/CRwyFPyk/1815-fix-syncs3todatabucket-scheduled-task
=> Memoize S3 and Elasticsearch client

Dockerfile, config.ru
Use puma directly in the Dockerfile
This should make it easier to pass more options to puma, I'm
particularly thinking of options concerning threads.
Link to Trello card: https://trello.com/c/knI00UhK/1851-use-puma-directly-for-the-logging-api
=> Use puma directly in the Dockerfile

Dockerfile
Use a minimum of 8 threads, and a maximum of 32. This is an increase on the values I see currently, which are a minimum
of 0 and a maximum of 5.
Not dropping down to 0 threads should help when new requests come in
and the service was previously idle. Allowing more threads should help
with handling more requests concurrently.
Link to Trello card: https://trello.com/c/Pxpt3w8e/1866-increase-puma-threads-for-the-logging-api
=> Use a minimum of 8 threads, and a maximum of 32

tasks/publish_statistics.rb
The load_env rake task dependency is now in first place for the publish_daily_metrics
rake task. The synchronize_ip_locations rake task now depends on the load_env task.
Otherwise the synchronize_ip_locations Rake task can't find any classes it depends on
=> Fix publish_daily_metrics rake task

lib/loader.rb
The number of Puma threads has been increased to a maximum of 32
and so to avoid Sequel::PoolTimeout errors we match the maximum
number of database connections.
See: https://github.com/alphagov/govwifi-logging-api/pull/498
=> Increase the Sequel connection pool

Rakefile, app.rb, lib/loader.rb
Don't specify a `read_timeout` for the USER_DB, and set the DB `read_timeout` to different values in different contexts.
I'm looking in to timeout issues when running some Rake tasks, and I'm hoping the longer (12 hour) timeout will help.
Link to Trello card: https://trello.com/c/tWoyciKg/2056-investigate-sentry-sequeldatabaseerror
=> Tweak read timeouts

README.md
Update the statistics commands in the README
I had to make a few changes when running these commands.
Remove the comment about ~/.aws/credentials, as that's out of
scope (people will probably use the gds-cli instead).
Link to Trello card: https://trello.com/c/tWoyciKg/2056-investigate-sentry-sequeldatabaseerror
=> Update the statistics commands in the README

lib/performance/use_case/completion_rate.rb, spec/lib/performance/metrics/metric_sender_spec.rb, spec/lib/performance/use_case/completion_rate_spec.rb
Add cumulative metrics to completion rate metrics
We want to know how many users have signed up over 3 journeys. (SMS/sponsored/Email) We
also want to know if they managed to sign in
https://trello.com/c/yRa3gd0W/2264-create-data-chart-on-grafana-to-show-new-users-that-have-signed-in
=> Add cumulative metrics to completion rate metrics

lib/gdpr/use_case/populate_user_last_login.rb, spec/lib/gdpr/use_case/populate_user_last_login_spec.rb, tasks/update_last_login.rb
Improve logging of the update_last_login rake task
###Why
We want to know when the task has started, which dates it uses
and how many records have been updated
This is to keep better track of how this task is performing
=> Improve logging of the update_last_login rake task

lib/gdpr/gateway/session.rb, spec/lib/gdpr/use_case/populate_user_last_login_spec.rb
Update active_users query to not use the 'Date' function
Running the query previously proved to be extremely slow. This is
because the Sessions table contains > 100 million rows and the query
used the "Date" function to select rows with a start attribute within
the specified day. This means that for each of the >100 million rows
the date function is applied which also makes it impossible for the
database to use the relevant index.
The change removes the 'Date' function from the query and instead
performs a direct comparison.
An extra test was introduced to ensure we select the correct Session
rows.
https://trello.com/c/yRa3gd0W/2264-create-data-chart-on-grafana-to-show-new-users-that-have-signed-in
=> Update active_users query to not use the 'Date' function

ci/tasks/deploy.yml
Make container name consistent with the name we use for the ECS service,
cluster and task definition. In our ECS task definitions we currently declare a container name that is different from the app, task and cluster name:
https://github.com/alphagov/govwifi-terraform/blob/13c45e4791ba82dfaba89cf68847eb2d720c4825/govwifi-api/logging-api-cluster.tf#L144
The name used is "logging" but elsewhere we use "logging-api" to refer
to related resources like the ECS service. This should be consistent -
"logging-api" should be used everywhere, and references to "logging"
should be deleted.
Using different values for the container name, service name and cluster name is confusing and makes writing the pipeline code more complicated.
This is related to PR: …
=> Rename concourse container name from 'logging' to 'logging-api'

buildspec.yml
Remove "STAGE" variable from buildspec file
The same docker image will now be used in production and staging. Removing the need for the "STAGE" variable.
Link to Jira card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-253
=> Remove "STAGE" variable from buildspec file

lib/performance/repository/session.rb, lib/performance/use_case/roaming_users.rb, mysql/migrations/20221123152200_add_success_site_ip_start_username_to_sessions.rb
The sessions table is getting very large and is slowing down the computation of roaming users.
It is optimised by omitting the time interval which is hard to write and index for and is replaced by selecting for dates greater than a day/week/month ago
An index is added to the sessions database to optimise this query, which now runs in around 6 minutes on an M1 mac laptop.
Link to Jira card (if applicable):  https://technologyprogramme.atlassian.net/browse/GW-599
=> Optimise the calculation of roaming users

tasks/migrate.rb
When running migrations, the output is now logged
Currently, when migrations run, they run silently. This makes it hard to debug.
=> Add logging to migration code

lib/smoketests/smoketest_cleanup.rb, spec/lib/performance/use_case/volumetrics_spec.rb, spec/lib/smoketests/smoketest_cleanup_spec.rb
The smoke tests have recently changed. They now take care of removing users that have been generated during the tests.
The Session data however still has to be removed. This is now done by siteIP and a new environment variable is introduced 'SMOKE_TEST_IPS' that lists all the site ips that the smoke tests use so that the correct sessions will be deleted.
See also: https://github.com/alphagov/govwifi-terraform/pull/794
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-895
=> Update the smoketest cleanup code

Gemfile.lock
gemfile.lock was missing platform x86_64-linux
=> adding missing bundler lock platform entry

lib/performance/metrics/metric_sender.rb, lib/performance/use_case/active_users.rb, lib/performance/use_case/completion_rate.rb, lib/performance/use_case/roaming_users.rb, lib/performance/use_case/volumetrics.rb, spec/lib/performance/metrics/metric_sender_spec.rb, spec/lib/performance/use_case/active_users_spec.rb, spec/lib/performance/use_case/completion_rate_spec.rb, spec/lib/performance/use_case/roaming_users_spec.rb, spec/lib/performance/use_case/volumetrics_spec.rb, tasks/publish_statistics.rb
This fixes an issue with the new user metrics and simplifies the passing of the date parameter.
=> Metric code now directly uses Date instead of string
